CALTECH_101 = "imbikramsaha/caltech-101"
YT_FACES = "selfishgene/youtube-faces-with-facial-keypoints"
FACE_DATASET = "jessicali9530/lfw-dataset"
OTHER_DATASET = "joaopauloschuler/cifar10-128x128-resized-via-cai-super-resolution"
NATURAL_IMAGES = "prasunroy/natural-images"
SCENES = "itsahmad/indoor-scenes-cvpr-2019"

DATA_CALTECH_101 = "data/caltech"
DATA_FACE_PATH = "data/face"
DATA_OTHER_PATH = "data/other"
DATA_YT_FACES = "data/yt_faces"
DATA_NATURAL_IMAGES = "data/natural_images"
DATA_SCENES = "data/scenes"
